version: '3'
services: 
  bot:
    container_name: bot
    build:
      context: ./
    restart: "always"
    #depends_on:
    # - postgresql
    #    condition: service_healthy

  postgresql:
    container_name: postgres
    image: postgres:9.6.12-alpine
    environment:
      POSTGRES_USER: sqluser
      POSTGRES_PASSWORD: sqlpass
      POSTGRES_DB: psql_db
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql/data4:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  #  healthcheck:
  #    test: [ "CMD-SHELL", "pg_isready -d postgres -U " ]
  #    interval: 1s
  #    timeout: 1s
  #    retries: 1500

