version: '2.3'
services: 
  bot:
    container_name: bot
    build:
      context: ./
    restart: "always"
    #depends_on:
    # - postgresql
    #    condition: service_healthy
    networks:
      default1:
        ipv4_address: 192.168.0.11

  postgresql:
    container_name: postgres
    image: postgres:9.6.12-alpine
    environment:
      POSTGRES_USER: sqluser
      POSTGRES_PASSWORD: sqlpass
      POSTGRES_DB: psql_db
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      default1:
        ipv4_address: 192.168.0.10
  #  healthcheck:
  #    test: [ "CMD-SHELL", "pg_isready -d postgres -U " ]
  #    interval: 1s
  #    timeout: 1s
  #    retries: 1500

networks:
  default1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
